language: node_js
node_js:
  - 'node'
  - '8'
  - '6.10.3'

install:
  - yarn global add codecov
  - yarn install --ignore-engines

script:
  - 'yarn test && nyc report --reporter=text-lcov > coverage.lcov && codecov'

notifications:
  email: false
