language: node_js
node_js:
  - 'node'
  - '8'
  - '6.10.3'
  - '4.3.2'

before_install:
  - '[[ "$(npm -v)" = 2* ]] && npm i -g npm@5'
  - 'export PATH="$PWD/scripts:$PATH"'
  - 'replace-yarn'

install:
  - yarn global add codecov
  - yarn install --ignore-engines

script:
  - 'yarn test # && nyc report --reporter=text-lcov > coverage.lcov && codecov'
