#!/usr/bin/env bash
set -eo pipefail

[[ "$(uname)" = *"Darwin"* ]] && echo 'not linux'
[[ "$(uname)" = *"Darwin"* ]] && echo 'exiting...'
[[ "$(uname)" = *"Darwin"* ]] && exit 1

[[ -z "$CI" ]] && echo 'not continuous integration'
[[ -z "$CI" ]] && echo 'exiting...'
[[ -z "$CI" ]] && exit 1

[[ "${echo $TRAVIS_NODE_VERSION | grep -o "[0-9]" | head -n1}" > '4' ]] echo 'not node 4'
[[ "${echo $TRAVIS_NODE_VERSION | grep -o "[0-9]" | head -n1}" > '4' ]] echo 'exiting...'
[[ "${echo $TRAVIS_NODE_VERSION | grep -o "[0-9]" | head -n1}" > '4' ]] exit 0


ORIGINAL="$(which yarn)"
SECOND="$(echo $PATH | awk -F ":" '{print $2}')/yarn"
OUTFILE="${ORIGINAL:-$SECOND}"

(
cat <<'EOF'
#!/usr/bin/env bash
set -exo pipefail

if [[ -z "$@" ]]; then
	npm install
elif [[ "$@" = *"global add"* ]]; then
	args = "$(echo "$@" | sed 's/global add/i -g/')"
	npm $args
else
	npm $@
fi

EOF
) > $OUTFILE

chmod +x "$OUTFILE"

(
cat <<'EOF'
#!/usr/bin/env bash
set -exo pipefail

if [[ -z "$@" ]]; then
	npm install
elif [[ "$@" = *"global add"* ]]; then
	args = "$(echo "$@" | sed 's/global add/i -g/')"
	npm $args
else
	npm $@
fi

EOF
) > ./scripts/yarn

chmod +x "./scripts/yarn"
