#!/usr/bin/env bash
set -eo pipefail

[[ "$(uname)" = *"Darwin"* ]] && echo 'not linux'
[[ "$(uname)" = *"Darwin"* ]] && echo 'exiting...'
[[ "$(uname)" = *"Darwin"* ]] && exit 1

[[ -z "$CI" ]] && echo 'not continuous integration'
[[ -z "$CI" ]] && echo 'exiting...'
[[ -z "$CI" ]] && exit 1

[[ "$(node --version | grep -o "[0-9]" | head -n1)" != '4' ]] && echo 'not node 4'
[[ "$(node --version | grep -o "[0-9]" | head -n1)" != '4' ]] && echo 'exiting...'
[[ "$(node --version | grep -o "[0-9]" | head -n1)" != '4' ]] && exit 0

(
cat <<'EOF'
#!/usr/bin/env bash
set -exo pipefail

if [[ -z "$@" ]]; then
	npm install
elif [[ "$@" = *"global add"* ]]; then
	args="$(echo "$@" | sed 's/global add/i -g/')"
	npm $args
else
	npm $@
fi

EOF
) > ./scripts/yarn

chmod +x "./scripts/yarn"
